export { default as Main } from "./Main";
export { default as Header } from "./Header";
export { default as OurTeam } from "./OurTeam";
export { default as AboutUs } from "./AboutUs";
export { Book } from "./Book";
export { default as Specialties } from "./Specialties";
export { default as Events } from "./Events";
export { default as Menu } from "./Menu";
export { default as Gallery } from "./Gallery";
export { default as Contact } from "./Contact";
export { default as Footer } from "./Footer";